<?php $loginOptional = true; include('settings_begin.inc.php') ?>

<h1 class="page-header">News</h1>

<?php /*
<div class="alert alert-warning" role="alert">
	<p>The PSK Reporter and RBN sources currently ignore FT4/FT8 spots on HF between 80-10m for the <a href="https://clublog.org/mostwanted.php">30 least wanted DXCCs</a> until further notice due to spot overload in the backend.</p>
</div>
*/ ?>

<h3>2025-06-01</h3>

<ul>
	<li>Switched to WWFF Spotline instead of WWFFwatch.</li>
</ul>

<h3>2025-03-09</h3>

<ul>
	<li>Added WWFFwatch as a spot source.</li>
</ul>


<h3>2024-07-22</h3>

<ul>
	<li>Notifications via SMS are now deprecated. Users who still have TextAnywhere credits are requested to use them up by the end of October 2024 (when SMS notifications will be removed).</li>
</ul>

<h3>2024-07-15</h3>

<ul>
	<li>Due to optimizations on the HamAlert backend (based on a proposal by KD0BTO), the CPU load of spot processing has been reduced, and therefore the filtering of FT4/FT8 spots from the least wanted DXCCs has been tentatively disabled. All spots from RBN and PSK Reporter are now processed again at the moment, while the situation is being reassessed.</li>
</ul>

<h3>2024-06-02</h3>

<ul>
	<li>The RBN is now also reporting millions of FT4/FT8 spots per day. Therefore, the existing filtering for FT4/FT8 spots between 80-10m for the 30 least wanted DXCCs has been extended to spots reported by the RBN.</li>
</ul>

<h3>2023-07-12</h3>

<ul>
	<li>The state that a POTA park is located in (according to the POTA database) may now override the spotted callsign's home state. This makes it possible to match on spots from POTA parks located in specific US states or Canadian provinces (e.g. by combining a “Park division = K/VE” condition with a “State = ...” condition). Note that some POTA parks span multiple states.</li>
</ul>

<h3>2023-06-06</h3>

<ul>
	<li>Added "Summit points" and "Summit activations" conditions. Useful for filtering out summits that are activated very frequently, hearing about first activations etc.</li>
</ul>

<h3>2023-04-15</h3>

<ul>
	<li>The <a href="https://forum.hamalert.org/">HamAlert Forum</a> is now live, and will serve as a place for users to ask questions, exchange advice and post feature requests.</li>
</ul>

<h3>2023-01-23</h3>

<ul>
	<li>With band conditions improving and the number of PSK Reporter spots steadily rising, FT4/FT8 spots from PSK Reporter (not from the RBN)
	    between 80-<strong>10m</strong> for the 30 least wanted DXCCs are now filtered.</li>
</ul>

<h3>2022-09-05</h3>

<ul>
	<li><strong>Email notifications will be discontinued on September 19, 2022.</strong>
		<ul>
			<li>The reason is an upcoming move to a new server infrastructure that makes sending the large amounts of email that HamAlert currently sends (about one million emails per month) more difficult than it already is, as well as long-standing problems with filtering and rate limiting by major mailbox hosting providers.</li>
			<li>Besides, emails are not really suitable for real-time information such as amateur radio spots anyway, as they may take several minutes to be delivered (greylisting, client polling intervals etc.).</li>
			<li>The preferred way to receive HamAlert notifications is to install the free HamAlert app on your smartphone. If you prefer an integration with the logging or cluster monitoring software on your computer, the Telnet interface may be useful (but a bit more tricky to set up and less reliable due to the lack of standardization of Telnet for transporting spots). Advanced users with coding experience can fashion their own integrations using the URL (webhook) destination.</li>
		</ul>
	</li>
</ul>

<h3>2022-05-27</h3>

<ul>
	<li>Added POTA (<a href="https://pota.app">https://pota.app</a>) as a spot source.</li>
</ul>

<h3>2022-03-01</h3>

<ul>
	<li>With band conditions improving and the number of PSK Reporter spots steadily rising, FT4/FT8 spots from PSK Reporter (not from the RBN)
	    between 80-<strong>15m</strong> for the 30 least wanted DXCCs are now filtered.</li>
</ul>

<h3>2021-12-26</h3>

<ul>
	<li>Added speed condition (CW WPM, for RBN spots).</li>
	<li>Added SNR condition (dB, for RBN and PSK reporter spots).</li>
</ul>

<h3>2021-03-31</h3>

<ul>
	<li>Added “spotter prefix” condition.</li>
</ul>

<h3>2021-03-07</h3>

<ul>
	<li>FT4/FT8 spots from the Reverse Beacon Network (RBN) are now also processed, and are <strong>not</strong> subject to any limits regarding bands or least wanted DXCCs.</li>
</ul>

<h3>2020-10-25</h3>

<ul>
	<li>App version 1.8:
		<ul>
			<li>Added a setting to use the local time instead of UTC within the app (does not apply to push notification contents, as those are generated by the server, but you can customize the push format on the <a href="/destinations">Destinations</a> page).</li>
			<li>Updated various libraries and frameworks.</li>
		</ul>
	</li>
</ul>

<h3>2020-10-22</h3>

<ul>
	<li>Only FT4/FT8 spots on 80-20m for the <strong>30</strong> least wanted DXCCs are now filtered.</li>
</ul>

<h3>2020-10-03</h3>

<ul>
	<li>FT4/FT8 spots from PSK Reporter on 160m are now also processed again for all DXCCs (including the 40 least wanted). Only FT4/FT8 spots on 80-20m
	for the 40 least wanted DXCCs are filtered.</li>
</ul>

<h3>2020-06-03</h3>

<ul>
	<li>Added “not Prefix” condition.</li>
</ul>

<h3>2020-05-16</h3>

<ul>
	<li>FT4/FT8 spots from PSK Reporter on 17m and higher bands are now processed again for all DXCCs (including the 40 least wanted).</li>
</ul>

<h3>2020-04-19</h3>

<ul>
	<li>FT4/FT8 spots from PSK Reporter on 6m and higher bands are now processed again for all DXCCs (including the 40 least wanted).</li>
</ul>

<h3>2020-03-22</h3>

<ul>
	<li><p>Upon the suggestion of a user, the PSK Reporter source has been enabled again but ignores FT4/FT8 spots for the 40
	least wanted DXCCs according to the <a href="https://clublog.org/mostwanted.php">Club Log DXCC Most Wanted List</a>.
	This greatly reduces the number of spots to be processed and makes HamAlert usable again for digimode DXing in the short term, although
	still unsuitable for some other purposes (e.g. WAS or monitoring for a friend's callsign etc.).</p>
	<p>Note that digimode spots from other sources (e.g. DX cluster spots tagged with "FT8" in the comments), and digimodes other than FT4 and FT8
		are not affected and continue to be processed as always.</p></li>
</ul>

<h3>2020-03-20</h3>

<ul>
	<li>The PSK Reporter source has been disabled for the time being. Since the beginning of the Corona virus crisis,
	PSK Reporter traffic has approximately doubled, reaching 23 million spots per day, or an average of more than 250 per second (!), with even higher peaks.
	Combined with an increase in HamAlert users and triggers, this is putting more load on the system than it can handle,
	negatively impacting the other spot sources (Cluster, RBN and SOTAwatch) by causing long notification delays. The problem with digimode spots is that
	almost every digimode user is also a spotter, and as the number of people who participate in digimodes grows,
	there is an almost exponential increase in the number of spots. I will investigate ways to
	solve this dilemma in the future, but at the moment, my priorities unfortunately do not allow a short-term solution.</li>
</ul>

<h3>2019-11-28</h3>

<ul>
	<li>The push notification format can now be customized on the <a href="/destinations">Destinations</a> page.</li>
</ul>

<h3>2019-11-03</h3>

<ul>
	<li>The PSK Reporter source has been enabled again.<br />Code optimizations and heuristics have made it possible to reduce the amount of CPU resources consumed by the matching engine. Further measures may be necessary as the number of PSK Reporter spots and HamAlert users continues to grow.</li>
</ul>

<h3>2019-11-02</h3>

<ul>
	<li>The PSK Reporter source had to be disabled for the time being due to backend overload.</li>
</ul>

<h3>2019-09-05</h3>

<ul>
	<li>Added a Telnet/Cluster emulation server, which allows you to receive alerts in any program that can connect to a DX cluster.</li>
</ul>

<h3>2019-09-05</h3>

<ul>
	<li>Added a Telnet/Cluster emulation server, which allows you to receive alerts in any program that can connect to a DX cluster.</li>
</ul>

<h3>2019-02-21</h3>

<ul>
	<li>Added callsign exclusion conditions: now you can exclude certain (spotter) callsigns, so you won't get an alert even if all other conditions match.</li>
</ul>

<h3>2019-01-14</h3>

<ul>
	<li>Added Prefix condition.</li>
</ul>

<h3>2019-01-12</h3>

<ul>
	<li>Added Spotter state condition.</li>
</ul>

<h3>2019-01-04</h3>

<ul>
	<li><strong>New year, new trigger conditions!</strong>
		<ul>
			<li><strong>State</strong>: matches on the state (currently US only) of the callsign according to the FCC database, updated weekly – use e.g. for WAS</li>
			<li><strong>QSL methods</strong>: matches based on whether the callsign appears on the list of active LoTW or eQSL AG members</li>
		</ul>
	</li>
	<li>App version 1.6: added a new, shorter notification sound (“Blip”).</li>
</ul>

<h3>2018-10-22</h3>

<ul>
	<li><strong>The PSK Reporter source has been enabled again for the time being.</strong><br />As a short-term measure to make it work again, more CPU power has been thrown at the matching engine to (hopefully) let it cope with the workload. Optimizations of the matching engine are still pending to make this scale in the future, and the PSK Reporter source may need to be disabled again until they are implemented. The current state of the PSK Reporter source will be shown at the top of this page.</li>
</ul>


<h3>2018-10-21</h3>

<ul>
	<li>The PSK Reporter source had to be disabled for the time being.<br />As the number of HamAlert users keeps growing while the volume of spots produced by PSK Reporter stays extremely high (due to the popularity of FT8 and the fact that almost every FT8 user is also an FT8 spotter, thus multiplying the number of spots for every single station), the PSK Reporter source is currently disabled and no PSK Reporter spots will be processed by HamAlert until a solution is found to process spots even faster. Spots from the RBN, the DX Cluster (including digimode spots) and SOTAwatch sources continue to be processed normally.</li>
</ul>


<h3>2018-06-11</h3>

<ul>
	<li>New version 1.5 of the HamAlert app: improved SOTA spot display, and fixed notification problems with Android 8+
	 (morse sounds now work again, and mute actions are available directly in the notification).</li>
</ul>


<h3>2018-04-01</h3>

<ul>
	<li>Unworked DXCCs can now also be loaded from Club Log, for those who aim to work all DXCCs but don't care about the band.
	Add a DXCC condition to use this feature.</li>
</ul>


<h3>2018-03-27</h3>

<ul>
	<li>Club Log DXCC matrix integration: you can now add a “Band slots” trigger condition that automatically pulls a list of
		band slots that you have not worked yet from Club Log.
		See the <a href="help#clublog">Help</a> page to get started.</li>
</ul>


<h3>2018-02-08</h3>

<ul>
	<li>App version 1.4: added a mute function to mute a certain callsign, callsign + band or callsign + summit combination for some time. Check the spot details
		(when you tap a spot) for the options, and the settings item in the app&apos;s menu. You can also mute callsigns or callsign + band combinations directly
		from the push notification.
		<ul><li><em>The update may take a few days to appear on the app stores for all platforms.</em></li></ul></li>
</ul>


<h3>2018-01-20</h3>

<ul>
	<li>Multiple park divisions and references can now be selected per trigger</li>
	<li>Added POTA references (<a href="https://www.parksontheair.com/">www.parksontheair.com</a>); WWFF and POTA divisions/parks can now be matched using the "Park division" or "Park reference" condition</li>
</ul>


<h3>2017-08-08</h3>

<ul>
	<li>Option to automatically update SOTA complete candidates once a day</li>
</ul>


<h3>2017-07-24</h3>

<ul>
	<li>Load an IOTA QSO CSV file (downloaded from rsgbiota.org) to automatically select all unworked references in an IOTA group condition</li>
</ul>


<h3>2017-07-13</h3>

<ul>
	<li>Mode (CW or SSB) is now guessed according to band plan for cluster spots</li>
</ul>


<h3>2017-07-11</h3>

<ul>
	<li>Added new digimodes to mode condition</li>
</ul>


<h3>2017-06-05</h3>

<ul>
	<li>Added an IOTA group reference condition (parsed from cluster spots)</li>
</ul>


<h3>2017-05-11</h3>

<ul>
	<li>More aggressive filtering on PSK Reporter spots to prevent false alerts<ul>
		<li>A quorum of three different spotters must be reached for the same combination of callsign/band/mode until spots are processed (spots are held back
			until the quorum is reached, and then all spots will be processed, so no spot is lost)</li>
		<li>Maximum spot age: 5 minutes</li>
	</ul></li>
</ul>


<h3>2017-05-07</h3>

<ul>
	<li>The “MySpot” dynamic image on the <a href="account">account page</a> allows you to embed information about the last spot for your callsign in other pages (your website, QRZ.com profile etc.).<br />
		<img src="images/myspot_example.png" style="margin-top: 1em" /><br /><p class="text-muted"><em>static example</em></p>
		</li>
</ul>


<h3>2017-05-05</h3>

<ul>
	<li>Lists of callsigns may now be entered (so you don't have to create lots of triggers for each of your friends, for example).</li>
	<li>Multiple values may now be selected for the following conditions:<ul>
		<li>Band</li>
		<li>Mode</li>
		<li>Source</li>
		<li>DXCC</li>
		<li>CQ zone</li>
		<li>Continent</li>
		<li>Summit association/reference</li>
	</ul></li>
</ul>


<h3>2017-05-02</h3>

<p>Behind-the-scenes change: a new custom high-performance matching engine has been implemented. This should allow HamAlert to scale easily beyond the
	~1500 triggers that are currently defined (and that have to be checked for every spot), and has become necessary now that the spot volume has
	increased massively due to the addition of the PSK Reporter source. Currently HamAlert processes about 20-30 spots per second.</p>
	
<p>As a side effect of the new engine, changes made to triggers, limits or destinations may now take up to a minute to apply as data is cached and optimized for fast lookups.</p>


<h3>2017-04-29</h3>

<ul>
	<li>New spot source PSK reporter (pskreporter.info, via gateway by DK1MAX and DL9GTB) added, which provides lots of JT65/JT9, PSK and other digimode spots</li>
	<li>New modes JT (includes JT65, JT9 etc.) and MSK (includes MSK144) added to mode condition</li>
	<li>New app version 1.1 with the following changes:<ul>
		<li>Swipe left to delete spots</li>
		<li>Added support for PSK Reporter source</li>
		<li>Shorter spot title</li>
		<li>SOTA summits and WWFF parks are now linked to info pages on the web</li>
		<li><em>iOS version may take a few days to appear on the App Store due to Apple review.</em></li>
	</ul>
	</li>
</ul>


<h3>2017-03-14</h3>

<ul>
	<li>The number of times that the general rate limit has been exceeded is now displayed on the <a href="limits">Limits</a> page</li>
</ul>


<h3>2017-03-05</h3>

<ul>
	<li>Added WWFF division/reference conditions (division can also be set to "*" to match any WWFF activation). WWFF references are extracted from DX cluster and SOTAwatch spot comments, and validated against the WWFF directory.</li>
	<li>SOTAwatch spots that contain the word "test" or "testing" (case-insensitive, but not other words in which "test" appears, like e.g. "contest") are now ignored</li>
	<li>New app version 1.0.3 published that properly displays WWFF spots (including a '44' morse sound for push notifications), and fixes some bugs
		<ul>
			<li>iOS version may take a few days to appear due to Apple review</li>
		</ul>
	</li>
</ul>


<h3>Outage 2017-02-25</h3>

<ul>
	<li>A prolonged power outage at the data center where the HamAlert server is hosted (affecting both circuits of the redundant power supplies) caused an outage between approx. 09:20 and 10:15 UTC. Unfortunately this also caused database corruption, so the backup taken at 00:00 UTC had to be restored. Changes made between 00:00 UTC and 10:15 UTC have been lost. Sorry for the inconvenience!</li>
</ul>


<h3>2017-02-15</h3>

<ul>
	<li>Added spotter CQ zone condition</li>
</ul>


<h3>2017-02-13</h3>

<ul>
	<li>Added support for secondary email address (= separate email address that can be enabled or disabled individually in triggers)
		<ul>
			<li>intended e.g. for use with email-to-SMS gateways</li>
		</ul></li>
	<li>Email subject and body format is now configurable with placeholders</li>
</ul>


<h3>2017-02-10</h3>

<ul>
	<li>SOTA Complete candidates loaded from the SOTA DB now only include summits that are still valid</li>
</ul>


<h3>2017-02-08</h3>

<ul>
	<li>Fixed a JavaScript compatibility issue that caused the "add trigger" button not to work on iOS 9</li>
</ul>


<h3>2017-02-06</h3>

<ul>
	<li>Added spotter continent condition</li>
	<li>Added a spot simulator for trigger/alert testing</li>
	<li>Added band range matching (e.g. HF, VHF, UHF etc.)</li>
	<li>Enable/disable push notifications per device on Destinations page</li>
	<li>App v1.0.2<ul>
		<li>previously seen spots are now marked as seen whenever the app is reopened</li>
		<li>spot details are shown when tapping a spot</li>
		<li>support for Morse sound in push notification ("DX", "RBN" or "SOTA"); configure on Destinations page</li>
		<li>Slider switch added in the side menu to enable/disable push</li>
		<li><em>App version v1.0.2 may take 1-2 days to appear on the App Store due to Apple review.</em></li>
	</ul></li>
</ul>

<h3>2017-02-04</h3>

<ul>
	<li>SOTA references are now also parsed from cluster spots</li>
</ul>

<?php include('settings_end.inc.php') ?>
